collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 1
color:
  saturation: 0.2293233
  brandStrength: 0.3238453
  lightness: 0.5741138
  brandColors:
    - '#FFFFFF'
    - '#0B0A08'
    - '#6A483D'
    - '#F0B188'
    - '#B77960'
  rhythmicContrast: 0
layout_spectrum: 0
name: Kirk Family
