collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.7051557
color:
  saturation: 0.6472533
  brandStrength: 0.3238453
  rhythmicContrast: 0.6327518
  brandColors:
    - '#FFFFFF'
    - '#0B0A08'
    - '#6A483D'
    - '#F0B188'
    - '#B77960'
  lightness: 0.2178185
layout_spectrum: 0.6632653
name: Kirk Family
